/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xzwzz_utils_bspatchUtils */

#ifndef _Included_com_xzwzz_utils_bspatchUtils
#define _Included_com_xzwzz_utils_bspatchUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xzwzz_utils_bspatchUtils
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xzwzz_utils_bspatchUtils_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
